version: '3.8'
services:
  postgres:
    image: postgres:latest
    ports:
      - 5200:5432
    container_name: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgrespw
      - POSTGRES_DB=nest
  test-postgres:
    image: postgres:latest
    ports:
      - 5435:5432
    container_name: test-postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgrespw
      - POSTGRES_DB=nest